import PageHeader from "@/components/PageHeader";

const distorsiones = [
  {
    nombre: "All-or-nothing thinking",
    descripcion: "Seeing situations in absolute, black-or-white categories, with no nuance or middle ground.",
    ejemplo: '"If I\'m not perfect, I\'m a complete failure."',
    alternativa: "Situations have degrees. One mistake does not invalidate the whole.",
  },
  {
    nombre: "Catastrophizing",
    descripcion: "Anticipating the worst possible outcome and treating it as inevitable or unbearable.",
    ejemplo: '"If my voice shakes, I\'ll fall apart completely and lose my job."',
    alternativa: "What is the real probability? Could I cope if it did happen?",
  },
  {
    nombre: "Overgeneralization",
    descripcion: "Drawing a sweeping conclusion from a single negative event.",
    ejemplo: '"I always ruin everything." (after one specific mistake).',
    alternativa: "A specific event does not define a universal pattern.",
  },
  {
    nombre: "Mental filter",
    descripcion: "Focusing exclusively on negative details while ignoring the positives.",
    ejemplo: '"The presentation was a disaster" (even though 90% went well).',
    alternativa: "Actively look for the positive aspects of the overall picture.",
  },
  {
    nombre: "Discounting the positive",
    descripcion: "Rejecting positive experiences by insisting they \"don't count for some reason\".",
    ejemplo: '"They complimented me out of luck, not because I did well."',
    alternativa: "Successes are just as real as failures.",
  },
  {
    nombre: "Mind reading",
    descripcion: "Assuming you know what others are thinking without real evidence.",
    ejemplo: '"I know they\'re thinking I\'m incompetent."',
    alternativa: "Do you have real evidence? Could you ask them directly?",
  },
  {
    nombre: "Fortune telling",
    descripcion: "Predicting that things will turn out badly and treating the prediction as a fact.",
    ejemplo: '"I know I won\'t get the job." (before the interview).',
    alternativa: "The future is not written. What are all the possible outcomes?",
  },
  {
    nombre: "Magnification / Minimization",
    descripcion: "Exaggerating the importance of problems while minimizing positive points.",
    ejemplo: '"My success was a fluke, but my mistake was terrible."',
    alternativa: "Use the same yardstick to evaluate achievements and errors.",
  },
  {
    nombre: "Emotional reasoning",
    descripcion: "Assuming that emotions reflect objective reality.",
    ejemplo: '"I feel stupid, therefore I am stupid."',
    alternativa: "Feelings are not facts. They can be distorted.",
  },
  {
    nombre: '"Should" statements',
    descripcion: "Holding rigid, inflexible rules about how oneself and others must behave.",
    ejemplo: '"I should be able to handle this on my own without help."',
    alternativa: "Replace \"should\" with \"I would prefer\" or \"it would be helpful if...\"",
  },
  {
    nombre: "Labeling",
    descripcion: "Attaching global negative labels to oneself or others.",
    ejemplo: '"I\'m an idiot" instead of "I made a mistake in this case".',
    alternativa: "Describe specific behaviors rather than labeling the person.",
  },
  {
    nombre: "Personalization",
    descripcion: "Taking personal responsibility for negative external events.",
    ejemplo: '"My child turned out badly because I failed as a parent."',
    alternativa: "What other factors contributed? Is it realistic to take all the blame?",
  },
];

const componentesCiclo = [
  {
    titulo: "SITUATION",
    descripcion: "The external or internal event that triggers the process",
    ejemplos: ["Receiving an email from the boss", "Noticing a physical symptom", "Seeing someone successful", "Remembering a difficult situation"],
    color: "bg-slate-100 border-slate-300",
    icon: "🌐",
  },
  {
    titulo: "THOUGHT",
    descripcion: "The interpretation or evaluation of the situation (automatic or deliberate)",
    ejemplos: ['"They\'ll fire me"', '"Something is wrong with my body"', '"I\'ll never achieve that"', '"I was a failure"'],
    color: "bg-blue-50 border-blue-300",
    icon: "💭",
  },
  {
    titulo: "EMOTION",
    descripcion: "The emotional response generated by the thought",
    ejemplos: ["Anxiety", "Fear", "Envy / sadness", "Guilt / shame"],
    color: "bg-amber-50 border-amber-300",
    icon: "❤️",
  },
  {
    titulo: "BEHAVIOR",
    descripcion: "What we do (or stop doing) in response",
    ejemplos: ["Checking the email 20 times", "Going to the emergency room", "Withdrawing", "Ruminating and not acting"],
    color: "bg-emerald-50 border-emerald-300",
    icon: "🎯",
  },
  {
    titulo: "CONSEQUENCES",
    descripcion: "The outcomes of the behavior that feed back into the cycle",
    ejemplos: ["More anxiety from waiting", "More hypervigilance", "More loneliness and depression", "The situation does not change"],
    color: "bg-rose-50 border-rose-300",
    icon: "🔄",
  },
];

const triadaBeck = [
  {
    aspecto: "Negative view of ONESELF",
    descripcion: "The individual sees themselves as flawed, inadequate, worthless, or unlovable.",
    ejemplos: ['"I\'m a failure"', '"I\'m good for nothing"', '"I\'m a burden to everyone"'],
    color: "border-blue-400",
  },
  {
    aspecto: "Negative view of the WORLD / EXPERIENCES",
    descripcion: "Interactions with the world are interpreted as defeats, deprivation, or humiliation.",
    ejemplos: ['"The world is unfair"', '"Things never work out"', '"Nobody supports me"'],
    color: "border-amber-400",
  },
  {
    aspecto: "Negative view of the FUTURE",
    descripcion: "When thinking about the future, the individual anticipates ongoing difficulties, deprivation, and failure.",
    ejemplos: ['"I\'ll never get better"', '"There\'s no point trying"', '"Things will always get worse"'],
    color: "border-rose-400",
  },
];

export default function ModeloCognitivoPage() {
  return (
    <div className="max-w-5xl mx-auto px-6 py-10">
      <PageHeader
        title="CBT Cognitive Model"
        description="The theoretical foundation of Cognitive-Behavioral Therapy: how thoughts, emotions, and behaviors are interrelated and mutually sustaining."
        badge="Fundamentals"
      />

      {/* The CBT Cycle */}
      <section className="mb-12">
        <h2 className="text-xl font-bold text-[#1e3a5f] mb-2">The Thought–Emotion–Behavior Cycle</h2>
        <p className="text-gray-600 mb-6 leading-relaxed">
          In CBT, the central element is not the situation itself but how we interpret it. The same situation can generate very different emotional responses in different people depending on their automatic thoughts.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
          {componentesCiclo.map((comp, i) => (
            <div key={comp.titulo} className={`rounded-xl border-2 p-4 ${comp.color} relative`}>
              {i < componentesCiclo.length - 1 && (
                <div className="hidden lg:block absolute -right-5 top-1/2 transform -translate-y-1/2 text-gray-400 text-xl z-10">
                  →
                </div>
              )}
              <div className="text-2xl mb-2">{comp.icon}</div>
              <h3 className="font-bold text-sm text-[#1e3a5f] mb-2">{comp.titulo}</h3>
              <p className="text-xs text-gray-600 mb-2 leading-relaxed">{comp.descripcion}</p>
              <ul className="space-y-1">
                {comp.ejemplos.map((ej) => (
                  <li key={ej} className="text-xs text-gray-500 italic">
                    {ej}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <div className="mt-4 bg-[#1e3a5f]/5 rounded-xl p-4 border border-[#1e3a5f]/20">
          <p className="text-sm text-[#1e3a5f] leading-relaxed">
            <strong>Core principle:</strong> CBT does not change situations (often impossible) but rather the interpretation of those situations. Changing the thought changes the emotion, and changing the emotion modifies behavior. This breaks the maintenance cycle of the problem.
          </p>
        </div>
      </section>

      {/* Beck's Cognitive Triad */}
      <section className="mb-12">
        <h2 className="text-xl font-bold text-[#1e3a5f] mb-2">Beck's Cognitive Triad (Depression)</h2>
        <p className="text-gray-600 mb-6 leading-relaxed">
          Aaron Beck identified in 1979 that people with depression systematically show a negative view in three areas. These three views reinforce each other and generate the vicious cycle of depression.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {triadaBeck.map((item) => (
            <div key={item.aspecto} className={`bg-white rounded-xl border-l-4 ${item.color} p-5 shadow-sm`}>
              <h3 className="font-bold text-[#1e3a5f] text-sm mb-3 leading-tight">{item.aspecto}</h3>
              <p className="text-gray-600 text-sm mb-3 leading-relaxed">{item.descripcion}</p>
              <div className="space-y-1">
                {item.ejemplos.map((ej) => (
                  <div key={ej} className="text-xs italic text-gray-500 bg-slate-50 rounded px-2 py-1">
                    {ej}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Levels of Cognition */}
      <section className="mb-12">
        <h2 className="text-xl font-bold text-[#1e3a5f] mb-2">The Three Levels of Cognition</h2>
        <p className="text-gray-600 mb-6 leading-relaxed">
          CBT organizes cognitive processes into three levels of depth, each with different characteristics and intervention strategies.
        </p>
        <div className="space-y-4">
          {[
            {
              nivel: "Level 1",
              nombre: "Automatic thoughts",
              descripcion: "Spontaneous, rapid, and often unconscious thoughts that occur in response to specific situations. They are the immediate 'inner dialogue'.",
              caracteristicas: ["Automatic and involuntary", "Specific to concrete situations", "Perceived as plausible and credible", "Can be verbal or in the form of images"],
              intervencion: "Thought records, Socratic questioning, evidence examination",
              color: "bg-blue-50 border-blue-200",
              textColor: "text-blue-700",
            },
            {
              nivel: "Level 2",
              nombre: "Dysfunctional assumptions and rules",
              descripcion: "Conditional beliefs of the 'If... then...' type or rigid rules about how things should be. They are deeper and more general than automatic thoughts.",
              caracteristicas: ["Conditional ('if I'm kind, they'll love me')", "Rigid rules ('I must be perfect')", "Inflexible attitudes about the world", "Less accessible than automatic thoughts"],
              intervencion: "Pros/cons analysis, rule challenging, downward arrow technique",
              color: "bg-amber-50 border-amber-200",
              textColor: "text-amber-700",
            },
            {
              nivel: "Level 3",
              nombre: "Core beliefs",
              descripcion: "Deep, global, and absolute beliefs about oneself, others, and the world. They are the core of the cognitive system and form early in life.",
              caracteristicas: ["Global and absolute ('I am worthless')", "Resistant to change", "Formed in childhood / adolescence", "Activated under stress"],
              intervencion: "Historical techniques, accumulated evidence review, alternative core beliefs, values work",
              color: "bg-rose-50 border-rose-200",
              textColor: "text-rose-700",
            },
          ].map((nivel) => (
            <div key={nivel.nivel} className={`rounded-xl border p-5 ${nivel.color}`}>
              <div className="flex items-start gap-4">
                <div className={`flex-shrink-0 font-bold text-xs px-2 py-1 rounded-full border ${nivel.color} ${nivel.textColor}`}>
                  {nivel.nivel}
                </div>
                <div className="flex-1">
                  <h3 className="font-bold text-[#1e3a5f] mb-1">{nivel.nombre}</h3>
                  <p className="text-gray-600 text-sm mb-3 leading-relaxed">{nivel.descripcion}</p>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <div className="text-xs font-semibold text-gray-500 uppercase mb-1">Characteristics</div>
                      <ul className="space-y-1">
                        {nivel.caracteristicas.map((c) => (
                          <li key={c} className="text-xs text-gray-600 flex items-start gap-1">
                            <span className="text-[#10b981] mt-0.5">•</span>
                            {c}
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <div className="text-xs font-semibold text-gray-500 uppercase mb-1">CBT Intervention</div>
                      <p className="text-xs text-gray-600 leading-relaxed">{nivel.intervencion}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Cognitive Distortions */}
      <section className="mb-12">
        <h2 className="text-xl font-bold text-[#1e3a5f] mb-2">Cognitive Distortions</h2>
        <p className="text-gray-600 mb-6 leading-relaxed">
          Cognitive distortions are systematic patterns of inaccurate or biased thinking that contribute to emotional distress. They are not personal 'flaws' but learned mental habits that can be modified.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {distorsiones.map((d) => (
            <div key={d.nombre} className="bg-white rounded-xl border border-slate-100 p-4 shadow-sm hover:shadow-md transition-shadow">
              <h3 className="font-semibold text-[#1e3a5f] mb-1">{d.nombre}</h3>
              <p className="text-gray-600 text-sm mb-2 leading-relaxed">{d.descripcion}</p>
              <div className="bg-red-50 rounded-lg px-3 py-2 mb-2">
                <span className="text-xs font-semibold text-red-600 uppercase">Example: </span>
                <span className="text-xs text-red-700 italic">{d.ejemplo}</span>
              </div>
              <div className="bg-emerald-50 rounded-lg px-3 py-2">
                <span className="text-xs font-semibold text-emerald-600 uppercase">Alternative: </span>
                <span className="text-xs text-emerald-700">{d.alternativa}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ABC Model */}
      <section className="mb-12">
        <h2 className="text-xl font-bold text-[#1e3a5f] mb-2">Ellis's ABC Model</h2>
        <p className="text-gray-600 mb-6 leading-relaxed">
          Albert Ellis (1955) developed the ABC model to explain the origin of emotional distress. The key insight is that it is not the events (A) that cause emotional consequences (C), but rather the beliefs (B) about those events.
        </p>
        <div className="bg-white rounded-xl border border-slate-100 p-6 shadow-sm">
          <div className="flex flex-col md:flex-row gap-6 items-start">
            {[
              { letra: "A", nombre: "Activating event", desc: "The activating event: the situation, fact, or experience that triggers the process.", ej: "The boss unexpectedly calls you into their office.", color: "bg-blue-600" },
              { letra: "B", nombre: "Beliefs", desc: "Beliefs about the event: the interpretations, evaluations, and meanings we give to the event.", ej: '"They\'re going to fire me. I must have made a serious mistake."', color: "bg-amber-500" },
              { letra: "C", nombre: "Consequences", desc: "The emotional and behavioral consequences of the beliefs (NOT of the event).", ej: "Intense anxiety, difficulty concentrating, catastrophic thoughts.", color: "bg-rose-500" },
              { letra: "D", nombre: "Disputation", desc: "Disputing irrational beliefs: challenging them with evidence, logic, and usefulness.", ej: '"What evidence do I have? Could there be another reason they called me?"', color: "bg-emerald-500" },
              { letra: "E", nombre: "Effect", desc: "The effect of disputation: new, more rational beliefs and more adaptive emotional consequences.", ej: "Moderate curiosity, controlled anxiety, flexible response.", color: "bg-purple-500" },
            ].map((item) => (
              <div key={item.letra} className="flex-1">
                <div className={`w-10 h-10 ${item.color} text-white rounded-full flex items-center justify-center font-bold text-xl mb-3`}>
                  {item.letra}
                </div>
                <div className="font-semibold text-[#1e3a5f] text-sm mb-1">{item.nombre}</div>
                <p className="text-xs text-gray-600 leading-relaxed mb-2">{item.desc}</p>
                <div className="bg-slate-50 rounded-lg p-2 text-xs text-gray-500 italic">{item.ej}</div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
